default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: diabolic
  password: diabolci
development:
  <<: *default
  database: diabolic_chat_development

test:
  <<: *default
  database: diabolic_chat_test

production:
  <<: *default
  database: diabolic-chat_production
  username: diabolic-chat
  password: <%= ENV['DIABOLIC-CHAT_DATABASE_PASSWORD'] %>
